### ISSUE TITLE
Unable to use pyJoules on Windows Subsystem for Linux?

### ISSUE THREAD

**Issue by kshivvy** [powerapi-ng/pyJoules#15]
I have the following code snippet running on Ubuntu 20.04 on Windows Subsystem for Linux (WSL). 

```
from pyJoules.energy_meter import measure_energy

@measure_energy
def foo():
    print("HERE")

foo()
```

I get the following stack trace error:

```
WARNING:root:pynvml not found you can't use NVIDIA devices
HERE
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    foo()
  File "/home/kshivvy/venv/lib/python3.8/site-packages/pyJoules/energy_meter.py", line 298, in wrapper_measure
    handler.process(energy_meter.get_trace())
  File "/home/kshivvy/venv/lib/python3.8/site-packages/pyJoules/energy_meter.py", line 160, in get_trace
    return self._generate_trace()
  File "/home/kshivvy/venv/lib/python3.8/site-packages/pyJoules/energy_meter.py", line 169, in _generate_trace
    domains = self._get_domain_list()
  File "/home/kshivvy/venv/lib/python3.8/site-packages/pyJoules/energy_meter.py", line 166, in _get_domain_list
    return reduce(operator.add, [device.get_configured_domains() for device in self.devices])
TypeError: reduce() of empty sequence with no initial value
```

Doe pyJoules support WSL?

**Comment by danglotb** [comment]
Hello @kshivvy,

I'm afraid that pyJoules does not support WSL. IHMO, it is because WSL does not provide the sysfs, which is the pseudo filesystem that allows pyJoules to measure the energy consumption, _i.e._ read RAPL. However, I'm not an expert, and contributors might confirm.

I think that it would be better, or easier would be more accurate, to have a complete Linux running directly on the machine.

Best,
Benjamin.
