### ISSUE TITLE
csv handler giving IndexError: list index out of range

### ISSUE THREAD

**Issue by j-j-kam** [powerapi-ng/pyJoules#25]
```
from pyJoules.energy_meter import measure_energy
from pyJoules.handler.csv_handler import CSVHandler

csv_handler = CSVHandler("./br_global_to_local2.csv")

global a, d
a = 5000
d = 3000


@measure_energy
def one():
    c = 4
    b = a * d * c
    return b


if __name__ == "__main__":

    for _ in range(10):
        one()

    csv_handler.save_data()
```

When trying to save the output in a csv, I get the following output:

```
WARNING:root:pynvml not found you can't use NVIDIA devices
begin timestamp : 1672598969.8471744; tag : one; duration : 0.0004711151123046875; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.847994; tag : one; duration : 0.00015354156494140625; package_0 : 24353.0; dram_0 : 2442.0; core_0 : 14160.0; uncore_0 : 0.0
begin timestamp : 1672598969.8482947; tag : one; duration : 0.0001442432403564453; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8485763; tag : one; duration : 0.000141143798828125; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8488526; tag : one; duration : 0.00014090538024902344; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8491614; tag : one; duration : 0.00015234947204589844; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8495045; tag : one; duration : 0.00014162063598632812; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8497858; tag : one; duration : 0.0001327991485595703; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8500986; tag : one; duration : 0.0001373291015625; package_0 : 31250.0; dram_0 : 2503.0; core_0 : 0.0; uncore_0 : 0.0
begin timestamp : 1672598969.8503737; tag : one; duration : 0.0001201629638671875; package_0 : 0.0; dram_0 : 0.0; core_0 : 0.0; uncore_0 : 0.0
Traceback (most recent call last):
  File "/dissertation/global_to_local/br_global_to_local.py", line 29, in <module>
    csv_handler.save_data()
  File "/dissertation/.venv/lib/python3.10/site-packages/pyJoules/handler/csv_handler.py", line 56, in save_data
    flatened_trace = self._flaten_trace()
  File "/dissertation/.venv/lib/python3.10/site-packages/pyJoules/handler/handler.py", line 59, in _flaten_trace
    if not _check_samples(flatened_trace):
  File "/dissertation/.venv/lib/python3.10/site-packages/pyJoules/handler/handler.py", line 31, in _check_samples
    sample1 = samples[0]
  File "/dissertation/.venv/lib/python3.10/site-packages/pyJoules/energy_trace.py", line 72, in __getitem__
    return self._samples[key]
IndexError: list index out of range
```

**Comment by j-j-kam** [comment]
Stupid error. Don't forget to add the handler as parameter to @measure_energy
